version: '3'
services:
  api:
    image: yeplink/rest-api
    build: .
    networks:
      - backend
    ports:
      - "3600:3600"

  web-cli:
    image: yeplink/rest-api
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
