version: '3'

services:
  api:
    env_file: .env
    image: yeplink/api-nodejs
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3600:3600
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    networks:
      - backend
    ports:
      - "27017:27017"

  web-cli:
    image: yeplink/api-nodejs
    links:
      - mongo
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
